// Code generated by mockery v2.20.0. DO NOT EDIT.

package service

import (
	model "Run_Hse_Run/pkg/model"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthorizationRepository is an autogenerated mock type for the AuthorizationRepository type
type MockAuthorizationRepository struct {
	mock.Mock
}

type MockAuthorizationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthorizationRepository) EXPECT() *MockAuthorizationRepository_Expecter {
	return &MockAuthorizationRepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: user
func (_m *MockAuthorizationRepository) CreateUser(user model.User) (int, error) {
	ret := _m.Called(user)

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(model.User) (int, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(model.User) int); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(model.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthorizationRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockAuthorizationRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - user model.User
func (_e *MockAuthorizationRepository_Expecter) CreateUser(user interface{}) *MockAuthorizationRepository_CreateUser_Call {
	return &MockAuthorizationRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", user)}
}

func (_c *MockAuthorizationRepository_CreateUser_Call) Run(run func(user model.User)) *MockAuthorizationRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.User))
	})
	return _c
}

func (_c *MockAuthorizationRepository_CreateUser_Call) Return(_a0 int, _a1 error) *MockAuthorizationRepository_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthorizationRepository_CreateUser_Call) RunAndReturn(run func(model.User) (int, error)) *MockAuthorizationRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: email
func (_m *MockAuthorizationRepository) GetUser(email string) (model.User, error) {
	ret := _m.Called(email)

	var r0 model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (model.User, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) model.User); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthorizationRepository_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockAuthorizationRepository_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - email string
func (_e *MockAuthorizationRepository_Expecter) GetUser(email interface{}) *MockAuthorizationRepository_GetUser_Call {
	return &MockAuthorizationRepository_GetUser_Call{Call: _e.mock.On("GetUser", email)}
}

func (_c *MockAuthorizationRepository_GetUser_Call) Run(run func(email string)) *MockAuthorizationRepository_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAuthorizationRepository_GetUser_Call) Return(_a0 model.User, _a1 error) *MockAuthorizationRepository_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthorizationRepository_GetUser_Call) RunAndReturn(run func(string) (model.User, error)) *MockAuthorizationRepository_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockAuthorizationRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockAuthorizationRepository creates a new instance of MockAuthorizationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockAuthorizationRepository(t mockConstructorTestingTNewMockAuthorizationRepository) *MockAuthorizationRepository {
	mock := &MockAuthorizationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
